apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: ecommerce
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: ghcr.io/nekoto-kun/order-service:latest
          imagePullPolicy: IfNotPresent
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: AMQP_URL
              value: amqp://rabbitmq.rabbit.svc.cluster.local:5672
