apiVersion: v1
kind: Service
metadata:
  labels:
    app: karsajobs-ui
  name: karsajobs-ui
  namespace: dicoding
spec:
  # Menggunakan tipe NodePort supaya bisa diakses dari luar cluster
  ports:
    - port: 8000
      nodePort: 30002
  selector:
    app: karsajobs-ui
  type: NodePort
