apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    name: ecommerce
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbit
  labels:
    name: rabbit
