apiVersion: v1
kind: Service
metadata:
  labels:
    app: karsajobs
  name: karsajobs
  namespace: dicoding
spec:
  ports:
    - port: 8080
      nodePort: 30001
  selector:
    app: karsajobs
  type: NodePort
