apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: ecommerce
spec:
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
        version: latest
      annotations:
        sidecar.istio.io/proxyCPU: 25m
        sidecar.istio.io/proxyCPULimit: 50m
        sidecar.istio.io/proxyMemory: 32Mi
        sidecar.istio.io/proxyMemoryLimit: 64Mi
    spec:
      containers:
        - name: shipping
          image: ghcr.io/nekoto-kun/shipping-service:latest
          imagePullPolicy: IfNotPresent
          resources: {}
          ports:
            - containerPort: 3001
          env:
            - name: AMQP_URL
              value: amqp://test:test@10.1.5.86:5672
