apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: dicoding
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  replicas: 1
  # Waktu tunggu sebelum dinyatakan available
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
    spec:
      # Tenggat waktu sebelum dimatikan seutuhnya
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          # Menggunakan MongoDB 3
          image: mongo:3
          env:
            # Mengambil kredensial MongoDB
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          ports:
            - containerPort: 27017
              name: mongo
          # Mount volume sebagai direktori untuk MongoDB
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: mongo-credentials
              mountPath: /etc/mongo-credentials
            - name: mongo-config
              mountPath: /config
      # Daftar volume yang akan digunakan MongoDB
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: mongo-credentials
          secret:
            secretName: mongo-secret
        - name: mongo-config
          configMap:
            name: mongo-config
